"""HTML report generation for Logsmith."""

from typing import List, Dict, Any
from .analysis import compute_stats


def generate_report(records: List[Dict], output_path: str, title: str = "Log Analysis Report") -> str:
    """Generate a standalone HTML report."""
    stats = compute_stats(records)

    # Generate ASCII bar chart data as inline SVG bars
    def bar_items(data, max_bars=15):
        if not data:
            return ""
        items = list(data)
        max_val = max(v for _, v in items[:max_bars]) if items else 1
        rows = ""
        for label, count in items[:max_bars]:
            pct = count / max_val * 100
            rows += f'<div class="bar-row"><span class="bar-label">{label}</span><div class="bar-bar"><div class="bar-fill" style="width:{pct}%"></div></div><span class="bar-count">{count}</span></div>\n'
        return rows

    # Status code summary
    status_summary = ""
    for code, count in sorted(stats.get("status_codes", {}).items()):
        color = "#22c55e" if str(code).startswith("2") else ("#eab308" if str(code).startswith("3") else "#ef4444")
        status_summary += f'<span class="status-badge" style="background:{color}">{code}: {count}</span>\n'

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #e2e8f0; padding: 2rem; }}
h1 {{ font-size: 2rem; margin-bottom: 0.5rem; }}
h2 {{ font-size: 1.4rem; margin: 1.5rem 0 0.5rem; color: #93c5fd; }}
.meta {{ color: #94a3b8; margin-bottom: 1.5rem; }}
.grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin-bottom: 2rem; }}
.stat {{ background: #1e293b; padding: 1.2rem; border-radius: 0.75rem; }}
.stat-value {{ font-size: 1.8rem; font-weight: 700; }}
.stat-label {{ font-size: 0.85rem; color: #94a3b8; margin-top: 0.25rem; }}
.card {{ background: #1e293b; border-radius: 0.75rem; margin-bottom: 1rem; overflow: hidden; }}
.card-header {{ background: #334155; padding: 0.75rem 1rem; font-weight: 600; font-size: 1.1rem; }}
.card-body {{ padding: 1rem; }}
.bar-row {{ display: flex; align-items: center; margin-bottom: 0.35rem; gap: 0.5rem; }}
.bar-label {{ width: 120px; font-size: 0.8rem; text-align: right; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }}
.bar-bar {{ flex: 1; background: #334155; height: 18px; border-radius: 4px; }}
.bar-fill {{ height: 100%; background: linear-gradient(90deg, #3b82f6, #60a5fa); border-radius: 4px; }}
.bar-count {{ width: 60px; font-size: 0.8rem; text-align: right; }}
.status-badge {{ display: inline-block; padding: 0.25rem 0.5rem; border-radius: 4px; margin: 0.15rem; font-size: 0.8rem; color: white; }}
.table {{ width: 100%; border-collapse: collapse; font-size: 0.85rem; }}
.table th {{ text-align: left; padding: 0.4rem 0.5rem; background: #334155; border-bottom: 2px solid #475569; }}
.table td {{ padding: 0.4rem 0.5rem; border-bottom: 1px solid #1e293b; font-family: monospace; }}
a {{ color: #60a5fa; }}
</style>
</head>
<body>
<h1>{title}</h1>
<p class="meta">Generated by Logsmith</p>

<div class="grid">
    <div class="stat">
        <div class="stat-value">{stats['total_lines']:,}</div>
        <div class="stat-label">Total Lines</div>
    </div>
    <div class="stat">
        <div class="stat-value">{stats['unique_ips']}</div>
        <div class="stat-label">Unique IPs</div>
    </div>
    <div class="stat">
        <div class="stat-value">{stats.get('status_codes', {}).get('200', 0):,}</div>
        <div class="stat-label">200 OK</div>
    </div>
    <div class="stat">
        <div class="stat-value">{stats.get('error_count', 0):,}</div>
        <div class="stat-label">Errors (4xx+5xx)</div>
    </div>
</div>

<h2>Status Codes</h2>
<div class="card">
    <div class="card-body">
        {status_summary}
    </div>
</div>

<h2>Top IPs</h2>
<div class="card">
    <div class="card-body">
        {bar_items(stats.get('top_ips', []))}
    </div>
</div>

<h2>Top Paths</h2>
<div class="card">
    <div class="card-body">
        {bar_items(stats.get('top_paths', []))}
    </div>
</div>

<h2>HTTP Methods</h2>
<div class="card">
    <div class="card-body">
        {bar_items(list(stats.get('methods', {}).items()))}
    </div>
</div>

<h2>User Agents</h2>
<div class="card">
    <div class="card-body">
        {bar_items(stats.get('top_agents', []))}
    </div>
</div>

<p style="margin-top:2rem;color:#64748b;font-size:0.8rem;">Generated by Logsmith — Log File Forensics Toolkit</p>
</body>
</html>"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    return output_path
